version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php-fpm
  php-fpm:
    build: ./docker/php-fpm
    image: php:7.3-fpm-alpine
    volumes:
      - ./src:/var/www/html
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: testdb
    volumes:
      - ./mysql-data:/var/lib/mysql
